### PR TITLE
Mac OS X support

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
The issue is the line `list(APPEND CMAKE_PREFIX_PATH $ENV{KIM_API_CMAKE_PREFIX_DIR})` in the cmake file, this overwrites the build prefix set by conda-forge.

**Comment by jan-janssen** [comment]
The issue is that `CC` is different for Linux and MacOs: 
```
CC=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc
CC=x86_64-apple-darwin13.4.0-clang
```

**Comment by ellio167** [comment]
@jan-janssen Thanks for the work here.  To explain a bit.  The CMakeLists.txt file tries to use the same compilers that were used to build the kim-api package.  Generally this is needed to ensure that the models will work correctly with the kim-api library.  It gets complicated in build systems  like conda (and homebrew) that modify the system build environment.

I think what you have done here is the correct approach in this case.

**Pull request merged**
